// ADR-100 §4.4 extension — title_en + source_url_en backfill
// Generated by scripts/gen_14c_cypher.py from law-note-de-fetched.json
// Only sets title_en where not null (gesetze-im-internet nodes skipped)

MATCH (l:Law {name: "CRA", article: "13"})
SET l.title_en = "Obligations of manufacturers", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R2847";

MATCH (l:Law {name: "CRA", article: "14"})
SET l.title_en = "Reporting obligations of manufacturers for actively exploited vulnerabilities and incidents", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R2847";

MATCH (l:Law {name: "DORA", article: "5"})
SET l.title_en = "ICT risk management framework", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2554";

MATCH (l:Law {name: "DORA", article: "6"})
SET l.title_en = "ICT risk management framework", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2554";

MATCH (l:Law {name: "DORA", article: "17"})
SET l.title_en = "ICT-related incident management process", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2554";

MATCH (l:Law {name: "DORA", article: "19"})
SET l.title_en = "Reporting of major ICT-related incidents and voluntary notification of significant cyber threats", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2554";

MATCH (l:Law {name: "DORA", article: "24"})
SET l.title_en = "General requirements for the performance of digital operational resilience testing", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2554";

MATCH (l:Law {name: "DORA", article: "28"})
SET l.title_en = "General principles for a sound management of ICT third-party risk", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2554";

MATCH (l:Law {name: "DSA", article: "5"})
SET l.title_en = "Exemptions for 'mere conduit'", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2065";

MATCH (l:Law {name: "DSA", article: "14"})
SET l.title_en = "Notice and action mechanisms", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2065";

MATCH (l:Law {name: "DSA", article: "26"})
SET l.title_en = "Advertising on online platforms", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2065";

MATCH (l:Law {name: "DSGVO", article: "5"})
SET l.title_en = "Principles relating to processing of personal data", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "6"})
SET l.title_en = "Lawfulness of processing", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "7"})
SET l.title_en = "Conditions for consent", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "13"})
SET l.title_en = "Information to be provided where personal data are collected from the data subject", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "14"})
SET l.title_en = "Information to be provided where personal data have not been obtained from the data subject", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "28"})
SET l.title_en = "Processor", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "30"})
SET l.title_en = "Records of processing activities", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "32"})
SET l.title_en = "Security of processing", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "33"})
SET l.title_en = "Notification of a personal data breach to the supervisory authority", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "35"})
SET l.title_en = "Data protection impact assessment", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "37"})
SET l.title_en = "Designation of the data protection officer", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "DSGVO", article: "46"})
SET l.title_en = "Transfers subject to appropriate safeguards", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679";

MATCH (l:Law {name: "EU AI Act", article: "4"})
SET l.title_en = "AI literacy", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "5"})
SET l.title_en = "Prohibited AI practices", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "6"})
SET l.title_en = "Classification rules for high-risk AI systems", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "9"})
SET l.title_en = "Risk management system", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "11"})
SET l.title_en = "Technical documentation", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "12"})
SET l.title_en = "Record-keeping", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "14"})
SET l.title_en = "Human oversight", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "26"})
SET l.title_en = "Obligations of deployers of high-risk AI systems", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "50"})
SET l.title_en = "Transparency obligations for providers and deployers of certain AI systems", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "51"})
SET l.title_en = "Registration of high-risk AI systems listed in Annex III", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "52"})
SET l.title_en = "Registration of certain AI systems listed in Annex III in the EU database", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "EU AI Act", article: "53"})
SET l.title_en = "Obligations for providers of general-purpose AI models", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689";

MATCH (l:Law {name: "NIS2", article: "2"})
SET l.title_en = "Scope", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";

MATCH (l:Law {name: "NIS2", article: "3"})
SET l.title_en = "Essential and important entities", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";

MATCH (l:Law {name: "NIS2", article: "4"})
SET l.title_en = "Sector-specific Union legal acts", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";

MATCH (l:Law {name: "NIS2", article: "6"})
SET l.title_en = "Definitions", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";

MATCH (l:Law {name: "NIS2", article: "7"})
SET l.title_en = "National cybersecurity strategy", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";

MATCH (l:Law {name: "NIS2", article: "10"})
SET l.title_en = "National cyber crisis management frameworks", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";

MATCH (l:Law {name: "NIS2", article: "21"})
SET l.title_en = "Cybersecurity risk-management measures", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";

MATCH (l:Law {name: "NIS2", article: "23"})
SET l.title_en = "Reporting obligations", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";

MATCH (l:Law {name: "NIS2", article: "24"})
SET l.title_en = "Use of European cybersecurity certification schemes", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";

MATCH (l:Law {name: "NIS2", article: "27"})
SET l.title_en = "European vulnerability database", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";

MATCH (l:Law {name: "NIS2", article: "32"})
SET l.title_en = "Supervisory and enforcement measures in relation to essential entities", l.source_url_en = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555";
