'use client'
import { useState, useRef, useEffect, useCallback } from 'react'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type EgoNode = { id: string; type: string; props: Record<string, any>; is_center: boolean }
type EgoEdge = { from: string; to: string; rel: string; direction: string }

const NODE_COLORS: Record<string, { fill: string; stroke: string }> = {
  Service:           { fill: '#1a1200', stroke: '#f59e0b' },
  Law:               { fill: '#0a1525', stroke: '#4a8fff' },
  DocumentType:      { fill: '#0d2b1f', stroke: '#4ade80' },
  Control:           { fill: '#1a0d0d', stroke: '#f87171' },
  UseCase:           { fill: '#1a0d1a', stroke: '#a78bfa' },
  Country:           { fill: '#0f1117', stroke: '#475569' },
  TransferMechanism: { fill: '#1a1200', stroke: '#f59e0b' },
  Risk:              { fill: '#1a0d0d', stroke: '#f87171' },
  RiskLevel:         { fill: '#1a0d0d', stroke: '#f87171' },
  Requirement:       { fill: '#0a1525', stroke: '#4a8fff' },
  Framework:         { fill: '#0f1117', stroke: '#475569' },
  AiRisk:            { fill: '#1a0d0d', stroke: '#f87171' },
}
const DEFAULT_COLOR = { fill: '#0f1117', stroke: '#475569' }

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max - 1) + '\u2026' : s
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildSimpleContext(nodeType: string, props: Record<string, any>): string | null {
  switch (nodeType) {
    case 'Law':
      return [
        props.applies_from || props.valid_from
          ? `Legal article in force since **${props.applies_from || props.valid_from}**.`
          : null,
        props.source || props.regulation
          ? `Source: **${props.source || props.regulation}**.`
          : null,
      ].filter(Boolean).join(' ') || null
    case 'Control':
      return [
        props.framework ? `Part of **${props.framework}**.` : null,
        props.severity ? `Severity: **${String(props.severity).toUpperCase()}**.` : null,
        props.default_tom_measure
          ? `Default measure: ${String(props.default_tom_measure).slice(0, 100)}...`
          : null,
      ].filter(Boolean).join(' ') || null
    case 'Service':
      return [
        props.country ? `Operated from **${props.country}**.` : null,
        props.gdpr_adequate === false ? 'No GDPR adequacy — SCCs required.' : null,
        props.dpa_url ? `DPA: ${props.dpa_url}` : null,
      ].filter(Boolean).join(' ') || null
    case 'DocumentType':
      return [
        `Document generated by the compliance pipeline.`,
        Array.isArray(props.required_sections)
          ? `Contains ${props.required_sections.length} mandatory sections.`
          : null,
      ].filter(Boolean).join(' ')
    case 'Country':
      return props.gdpr_adequate === false
        ? `No GDPR adequacy decision. SCCs + TIA required for data transfers.`
        : `GDPR adequacy decision exists.`
    default:
      return null
  }
}

type PositionedNode = EgoNode & { x: number; y: number; r: number }

export default function EgoGraph({
  nodes,
  edges,
  centerId,
  onNodeClick,
}: {
  nodes: EgoNode[]
  edges: EgoEdge[]
  centerId: string
  onNodeClick: (node: EgoNode) => void
}) {
  const containerRef = useRef<HTMLDivElement>(null)
  const [size, setSize] = useState({ w: 800, h: 500 })
  const [hovered, setHovered] = useState<string | null>(null)
  const [mousePos, setMousePos] = useState({ x: 0, y: 0 })
  const [panelNode, setPanelNode] = useState<EgoNode | null>(null)

  // Responsive sizing
  useEffect(() => {
    const el = containerRef.current
    if (!el) return
    const obs = new ResizeObserver(entries => {
      const { width, height } = entries[0].contentRect
      setSize({ w: Math.max(width, 400), h: Math.max(height, 400) })
    })
    obs.observe(el)
    return () => obs.disconnect()
  }, [])

  const handleMouseMove = useCallback((e: React.MouseEvent<SVGSVGElement>) => {
    const rect = e.currentTarget.getBoundingClientRect()
    setMousePos({ x: e.clientX - rect.left, y: e.clientY - rect.top })
  }, [])

  // Layout: center node in middle, neighbors in circle
  const panelWidth = panelNode ? 320 : 0
  const canvasWidth = size.w - panelWidth
  const cx = canvasWidth / 2
  const cy = size.h / 2
  const radius = Math.min(cx, cy) * 0.6

  const center = nodes.find(n => n.id === centerId)
  const neighbors = nodes.filter(n => n.id !== centerId)

  const positioned: PositionedNode[] = []
  if (center) {
    positioned.push({ ...center, x: cx, y: cy, r: 44 })
  }
  neighbors.forEach((n, i) => {
    const angle = (i / neighbors.length) * 2 * Math.PI - Math.PI / 2
    positioned.push({
      ...n,
      x: cx + radius * Math.cos(angle),
      y: cy + radius * Math.sin(angle),
      r: 28,
    })
  })

  const nodeMap = new Map(positioned.map(n => [n.id, n]))

  // Tooltip data
  const hoveredNode = hovered ? nodeMap.get(hovered) : null

  const PROP_SKIP = new Set(['text', 'title', 'title_en', 'id', 'name', 'type', 'description'])

  return (
    <div
      ref={containerRef}
      style={{
        width: '100%',
        minHeight: '400px',
        height: '100%',
        background: '#080b12',
        borderRadius: '6px',
        border: '1px solid var(--border-default)',
        position: 'relative',
        overflow: 'hidden',
        display: 'flex',
      }}
    >
      {/* Graph canvas */}
      <svg
        width={canvasWidth}
        height={size.h}
        style={{ display: 'block', flexShrink: 0 }}
        onMouseMove={handleMouseMove}
      >
        <defs>
          <marker
            id="arrow-out"
            viewBox="0 0 10 6"
            refX="10"
            refY="3"
            markerWidth="8"
            markerHeight="6"
            orient="auto"
          >
            <path d="M0,0 L10,3 L0,6" fill="#4a8fff" opacity="0.8" />
          </marker>
          <marker
            id="arrow-in"
            viewBox="0 0 10 6"
            refX="10"
            refY="3"
            markerWidth="8"
            markerHeight="6"
            orient="auto"
          >
            <path d="M0,0 L10,3 L0,6" fill="#475569" opacity="0.6" />
          </marker>
        </defs>

        {/* Edges */}
        {edges.map((edge, i) => {
          const from = nodeMap.get(edge.from)
          const to = nodeMap.get(edge.to)
          if (!from || !to) return null

          // Shorten line to stop at node border
          const dx = to.x - from.x
          const dy = to.y - from.y
          const dist = Math.sqrt(dx * dx + dy * dy)
          if (dist === 0) return null
          const ux = dx / dist
          const uy = dy / dist

          const x1 = from.x + ux * (from.r + 2)
          const y1 = from.y + uy * (from.r + 2)
          const x2 = to.x - ux * (to.r + 6)
          const y2 = to.y - uy * (to.r + 6)

          const mx = (x1 + x2) / 2
          const my = (y1 + y2) / 2

          const isOut = edge.direction === 'out'

          return (
            <g key={i}>
              <line
                x1={x1} y1={y1} x2={x2} y2={y2}
                stroke={isOut ? '#4a8fff' : '#475569'}
                strokeWidth={1.5}
                opacity={isOut ? 0.7 : 0.4}
                markerEnd={isOut ? 'url(#arrow-out)' : 'url(#arrow-in)'}
              />
              <text
                x={mx}
                y={my - 6}
                textAnchor="middle"
                fontSize="9"
                fontFamily="ui-monospace, monospace"
                fill="#4a8fff"
                opacity={0.85}
              >
                {edge.rel}
              </text>
            </g>
          )
        })}

        {/* Nodes */}
        {positioned.map(node => {
          const colors = NODE_COLORS[node.type] || DEFAULT_COLOR
          const isCenter = node.id === centerId
          const isHovered = hovered === node.id
          const isPanelActive = panelNode?.id === node.id
          const label = truncate(node.id, isCenter ? 18 : 12)

          return (
            <g
              key={node.id}
              style={{ cursor: isCenter ? 'default' : 'pointer' }}
              onClick={() => {
                if (!isCenter) {
                  setPanelNode(node)
                }
              }}
              onMouseEnter={() => setHovered(node.id)}
              onMouseLeave={() => setHovered(null)}
            >
              <circle
                cx={node.x}
                cy={node.y}
                r={node.r}
                fill={colors.fill}
                stroke={isPanelActive ? '#fff' : colors.stroke}
                strokeWidth={isCenter ? 2 : isPanelActive ? 2.5 : 1.5}
                opacity={isHovered || isPanelActive ? 1 : 0.9}
                filter={isHovered ? 'brightness(1.3)' : undefined}
              />
              {/* Type label (small, above) */}
              <text
                x={node.x}
                y={node.y - (isCenter ? 8 : 4)}
                textAnchor="middle"
                fontSize={isCenter ? '9' : '8'}
                fontFamily="ui-monospace, monospace"
                fill={colors.stroke}
                opacity={0.7}
                letterSpacing="0.04em"
              >
                {node.type}
              </text>
              {/* ID label */}
              <text
                x={node.x}
                y={node.y + (isCenter ? 6 : 5)}
                textAnchor="middle"
                fontSize={isCenter ? '11' : '9'}
                fontFamily="ui-monospace, monospace"
                fill="#e2e8f0"
                fontWeight={isCenter ? 600 : 400}
              >
                {label}
              </text>
            </g>
          )
        })}
      </svg>

      {/* Tooltip (only when panel is not open for this node) */}
      {hoveredNode && hoveredNode.id !== centerId && panelNode?.id !== hoveredNode.id && (
        <div
          style={{
            position: 'absolute',
            left: Math.min(mousePos.x + 12, size.w - 200),
            top: Math.min(mousePos.y - 10, size.h - 100),
            background: '#0d1117',
            border: '1px solid rgba(255,255,255,0.12)',
            borderRadius: '4px',
            padding: '8px 12px',
            pointerEvents: 'none',
            zIndex: 10,
            minWidth: '140px',
            maxWidth: '240px',
          }}
        >
          <div style={{
            fontSize: '9px',
            color: (NODE_COLORS[hoveredNode.type] || DEFAULT_COLOR).stroke,
            fontFamily: 'ui-monospace, monospace',
            letterSpacing: '0.06em',
            marginBottom: '4px',
            textTransform: 'uppercase',
          }}>
            {hoveredNode.type}
          </div>
          <div style={{
            fontSize: '12px',
            color: '#e2e8f0',
            fontFamily: 'ui-monospace, monospace',
            fontWeight: 500,
            marginBottom: '4px',
          }}>
            {hoveredNode.id}
          </div>
          <div style={{ fontSize: '9px', color: '#475569', fontFamily: 'ui-monospace, monospace', marginTop: '4px' }}>
            click to inspect
          </div>
        </div>
      )}

      {/* Side panel — node context */}
      {panelNode && (
        <div style={{
          width: `${panelWidth}px`,
          flexShrink: 0,
          background: '#0d1117',
          borderLeft: '1px solid var(--border-default)',
          overflowY: 'auto',
          padding: '16px',
        }}>
          {/* Close button */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
            <span style={{
              fontSize: '9px',
              color: (NODE_COLORS[panelNode.type] || DEFAULT_COLOR).stroke,
              fontFamily: 'ui-monospace, monospace',
              letterSpacing: '0.06em',
              textTransform: 'uppercase',
            }}>
              {panelNode.type}
            </span>
            <span
              onClick={() => setPanelNode(null)}
              style={{ fontSize: '14px', color: 'var(--text-muted)', cursor: 'pointer', lineHeight: 1 }}
            >
              ✕
            </span>
          </div>

          {/* Node ID */}
          <div style={{
            fontSize: '16px',
            fontWeight: 600,
            color: '#e2e8f0',
            fontFamily: 'ui-monospace, monospace',
            marginBottom: '4px',
          }}>
            {panelNode.id}
          </div>
          {(panelNode.props.title || panelNode.props.title_en) && (
            <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginBottom: '12px' }}>
              {panelNode.props.title || panelNode.props.title_en}
            </div>
          )}

          {/* WHY THIS MATTERS — props-only version */}
          {(() => {
            const ctx = buildSimpleContext(panelNode.type, panelNode.props)
            if (!ctx) return null
            const html = ctx.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
            return (
              <div style={{
                background: 'rgba(74,143,255,0.05)',
                border: '1px solid rgba(74,143,255,0.18)',
                borderLeft: '3px solid var(--accent)',
                borderRadius: '6px',
                padding: '12px 14px',
                marginBottom: '14px',
              }}>
                <div style={{
                  fontSize: '9px', color: 'var(--accent)', letterSpacing: '0.1em',
                  fontWeight: 600, marginBottom: '6px', fontFamily: 'ui-monospace, monospace',
                }}>
                  WHY THIS MATTERS
                </div>
                <p
                  dangerouslySetInnerHTML={{ __html: html }}
                  style={{
                    fontSize: '11px', color: 'var(--text-secondary)', lineHeight: '1.6',
                    fontFamily: 'Inter, system-ui, sans-serif', margin: 0,
                  }}
                />
              </div>
            )
          })()}

          {/* Key properties */}
          <div style={{
            background: 'rgba(255,255,255,0.03)',
            borderRadius: '4px',
            padding: '10px 12px',
            marginBottom: '14px',
          }}>
            {panelNode.props.confidence !== undefined && (
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '3px 0' }}>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)', fontFamily: 'ui-monospace, monospace' }}>confidence</span>
                <span style={{ fontSize: '10px', color: 'var(--state-pass)', fontFamily: 'ui-monospace, monospace' }}>{panelNode.props.confidence}</span>
              </div>
            )}
            {panelNode.props.severity && (
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '3px 0' }}>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)', fontFamily: 'ui-monospace, monospace' }}>severity</span>
                <span style={{ fontSize: '10px', color: 'var(--state-warn)', fontFamily: 'ui-monospace, monospace' }}>{String(panelNode.props.severity).toUpperCase()}</span>
              </div>
            )}
            {panelNode.props.framework && (
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '3px 0' }}>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)', fontFamily: 'ui-monospace, monospace' }}>framework</span>
                <span style={{ fontSize: '10px', color: 'var(--text-secondary)', fontFamily: 'ui-monospace, monospace' }}>{panelNode.props.framework}</span>
              </div>
            )}
            {Object.entries(panelNode.props)
              .filter(([k]) => !PROP_SKIP.has(k) && !['confidence', 'severity', 'framework', 'default_tom_measure'].includes(k))
              .slice(0, 6)
              .map(([key, value]) => (
                <div key={key} style={{ display: 'flex', justifyContent: 'space-between', gap: '12px', padding: '3px 0' }}>
                  <span style={{ fontSize: '10px', color: 'var(--text-muted)', fontFamily: 'ui-monospace, monospace', flexShrink: 0 }}>{key}</span>
                  <span style={{ fontSize: '10px', color: 'var(--text-secondary)', fontFamily: 'ui-monospace, monospace', textAlign: 'right', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {Array.isArray(value) ? value.join(', ') : String(value)}
                  </span>
                </div>
              ))
            }
          </div>

          {/* Open in Inspector */}
          <div
            onClick={() => onNodeClick(panelNode)}
            style={{
              fontSize: '11px',
              color: 'var(--accent)',
              cursor: 'pointer',
              fontFamily: 'ui-monospace, monospace',
              padding: '8px 0',
              borderTop: '1px solid var(--border-default)',
              textAlign: 'center',
            }}
            onMouseEnter={e => { e.currentTarget.style.textDecoration = 'underline' }}
            onMouseLeave={e => { e.currentTarget.style.textDecoration = 'none' }}
          >
            Open in Inspector →
          </div>
        </div>
      )}
    </div>
  )
}
