"""
Disclaimer helper — fetches localised disclaimer text from Supabase.

Disclaimer text lives in disclaimer_templates (lang, doc_type).
Lookup: specific doc_type first, then NULL fallback.
Results are cached for the lifetime of the process (one DB hit per unique key).
"""

import logging
import os
from functools import lru_cache

import psycopg2
import psycopg2.extras

from src.graph.asset_translator import _resolve_db_url

logger = logging.getLogger(__name__)

# doc_type keys used in architect — must match disclaimer_templates rows exactly
DOC_TYPE_MAP = {
    "AVV":                    "avv",
    "TOM":                    "tom",
    "AI_Act_Manifest":        "ai_act",
    "VVT":                    "vvt",
    "KI_System_Dokumentation": None,  # generic fallback
    "KI_Policy":              None,
    "SCC":                    None,
    "DSFA":                   None,
}

# Hedging substitutions applied to rendered template body.
# Tuple: (exact_match, replacement) — applied left to right, case-sensitive.
HEDGING_SUBSTITUTIONS = [
    ("Rechtsgrundlage:",        "Mögliche Rechtsgrundlage (zu prüfen):"),
    ("Risikostufe:",            "Vorgeschlagene Risikoeinstufung (nicht verbindlich):"),
    ("ist verpflichtet",        "wird empfohlen zu vereinbaren, dass"),
    ("Legal basis:",            "Possible legal basis (to be verified):"),
    ("Risk level:",             "Proposed risk classification (non-binding):"),
]


@lru_cache(maxsize=64)
def _fetch_disclaimer(lang: str, doc_type_key: str | None) -> str | None:
    """
    Query disclaimer_templates for (lang, doc_type_key).
    Returns content string or None if not found / DB unavailable.
    Result is cached per (lang, doc_type_key) pair.
    """
    db_url = _resolve_db_url()
    if not db_url:
        logger.warning("disclaimer: no DB URL — returning None")
        return None
    try:
        with psycopg2.connect(db_url) as conn:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
                if doc_type_key:
                    cur.execute(
                        "SELECT content FROM disclaimer_templates "
                        "WHERE lang = %s AND doc_type = %s LIMIT 1",
                        (lang, doc_type_key),
                    )
                    row = cur.fetchone()
                    if row:
                        return row["content"]
                # NULL fallback
                cur.execute(
                    "SELECT content FROM disclaimer_templates "
                    "WHERE lang = %s AND doc_type IS NULL LIMIT 1",
                    (lang,),
                )
                row = cur.fetchone()
                return row["content"] if row else None
    except Exception as exc:
        logger.warning("disclaimer: DB error — %s", exc)
        return None


def get_disclaimer(doc_type: str | None = None, lang: str | None = None) -> str:
    """
    Return the disclaimer header for a given document type.

    ADR-079 2a: `lang` is now an explicit parameter (render-time document
    language). The LEGAL_DOCS_LANG environment variable is only the fallback
    when no `lang` is passed, preserving the previous default behaviour.
    Lookup order: (lang, doc_type) → (lang, NULL) → hard-coded minimal fallback.

    Args:
        doc_type: Architect doc_type key e.g. 'AVV', 'TOM', 'AI_Act_Manifest'.
                  Pass None for a generic disclaimer.
        lang: Document language ('de'/'en'). Falls back to LEGAL_DOCS_LANG env
              (default 'de') when None.

    Returns:
        Disclaimer text ready to prepend to the document body.
    """
    if lang is None:
        lang = os.environ.get("LEGAL_DOCS_LANG", "de")
    lang = lang.lower()[:2]
    db_key = DOC_TYPE_MAP.get(doc_type) if doc_type else None
    text = _fetch_disclaimer(lang, db_key)
    if text:
        return text

    # Hard-coded fallback — never None, no DB required
    if lang == "en":
        return (
            "---\n"
            "⚠️ AUTO-GENERATED DRAFT – NOT LEGAL ADVICE\n\n"
            "This document must be reviewed by a qualified legal professional before use.\n\n"
            "Generated by Lex-Orchestra (AGPL-3.0)\n"
            "---"
        )
    return (
        "---\n"
        "⚠️ ENTWURF — ARBEITSGRUNDLAGE, KEINE RECHTSBERATUNG\n\n"
        "Lex-Orchestra dokumentiert die erkannten technischen Systeme und Datenflüsse "
        "und leitet daraus diesen Entwurf ab. Er dient als Arbeitsgrundlage für "
        "Datenschutz-, Compliance- und Rechtsberatung und ersetzt keine individuelle "
        "rechtliche Prüfung. Vor produktivem Einsatz ist eine fachliche Prüfung erforderlich.\n\n"
        "Erstellt von Lex-Orchestra (AGPL-3.0)\n"
        "---"
    )


def get_confidence_block(score: float, lang: str = "de") -> str:
    """Removed per ADR-085: honest absence beats a fake score."""
    return ""


def apply_hedging(content: str) -> str:
    """
    Apply linguistic hedging substitutions to a rendered document body.

    Replaces assertive legal phrases with qualified, non-binding equivalents
    to make it clear the document was auto-generated.

    Args:
        content: Rendered document string.

    Returns:
        Document string with hedging substitutions applied.
    """
    for original, replacement in HEDGING_SUBSTITUTIONS:
        content = content.replace(original, replacement)
    return content
